version: 2

sources:
  - name : raw
    description: "raw input data from kaggle"
    dataset: needle
    tables:
      - name: olist_customers_dataset
        description: "olist_customers_dataset"

      - name: olist_geolocation_dataset
        description: "olist_geolocation_dataset"

      - name: olist_order_items_dataset
        description: "olist_order_items_dataset"

      - name: olist_order_payments_dataset
        description: "olist_order_payments_dataset"

      - name: olist_order_reviews_dataset
        description: "olist_order_reviews_dataset"
      
      - name: olist_orders_dataset
        description: "olist_orders_dataset"
      
      - name: olist_products_dataset
        description: "olist_products_dataset"
      
      - name: olist_sellers_dataset
        description: "olist_sellers_dataset"

      - name: product_category_name_translation
        description: "product_category_name_translation"